GET https://localhost:7083/api/biologo

###

GET https://localhost:7083/api/biologo/Nombre/Nombre1

###

GET https://localhost:7083/api/biologo/Id/4

###

POST https://localhost:7083/api/biologo
Content-Type: application/json

{
    "Correo_biologo": "Antonio@hotmail.com",
    "Nombre_biologo": "Antonio",
    "Edad_biologo": 22,
    "Telefono_biologo": 2288563129,
    "Contrasena_biologo": "antoniopassword",
    "Usuario_biologo": "manzano1717"
}

###

PUT https://localhost:7083/api/biologo/8
Content-Type: application/json

{
    "Id_biologo": 8,
    "Correo_biologo": "pruebaPUT@pruebas.com",
    "Nombre_biologo": "NombrePruebaPUT",
    "Edad_biologo": 27,
    "Telefono_biologo": 2721847177,
    "Contrasena_biologo": "passwordPUT",
    "Usuario_biologo": "user001PUT"
}

###

DELETE https://localhost:7083/api/biologo/1

###
GET https://localhost:5001/api/pregunta