GET https://localhost:5001/api/biologo
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zaWQiOiJlZTBmMmNiNC1hNzIzLTQ5OTgtOTkyYi02MTZkMDU2MjA4MmEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiTm9tYnJlMSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluaXN0cmFkb3IiLCJleHAiOjE3MTYzMzMzMzgsImlzcyI6IlNlcnZpZG9yQ1NoYXJwIiwiYXVkIjoiQ2xpZW50ZUNTaGFycCJ9.xnSRhwxAE52UYCaf-iybQBII4SBvf3MvLxMIOUTrW9k

###

GET https://localhost:7083/api/biologo/Nombre/Nombre1

###

GET https://localhost:7083/api/biologo/Id/4

###

POST https://localhost:5001/api/biologo
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zaWQiOiIyYzJjZjBhYy0yZmI0LTRlMDgtOThiMy1kYTFkYWE5ZDhhNTYiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiTm9tYnJlMSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluaXN0cmFkb3IiLCJleHAiOjE3MTcyNzQ2MzEsImlzcyI6IlNlcnZpZG9yQ1NoYXJwIiwiYXVkIjoiQ2xpZW50ZUNTaGFycCJ9.RltQebpzLlEXB5Si7WHmuQ51XtXTiLro72OWE2KkCq4"

{
    "Correo_biologo": "Antonio@hotmail.com",
    "Nombre_biologo": "Antonio",
    "Edad_biologo": 22,
    "Telefono_biologo": 2288563129,
    "Contrasena_biologo": "antoniopassword",
    "Usuario_biologo": "manzano1717"
}

###

PUT https://localhost:7083/api/biologo/8
Content-Type: application/json

{
    "Id_biologo": 8,
    "Correo_biologo": "pruebaPUT@pruebas.com",
    "Nombre_biologo": "NombrePruebaPUT",
    "Edad_biologo": 27,
    "Telefono_biologo": 2721847177,
    "Contrasena_biologo": "passwordPUT",
    "Usuario_biologo": "user001PUT"
}

###

DELETE https://localhost:7083/api/biologo/1

###
GET https://localhost:5001/api/pregunta