GET https://localhost:7083/api/escarabajo

###

PUT https://localhost:7083/api/escarabajo/put/especie1
Content-Type: application/json

{
    "Especie_escarabajo": "especie1",
    "Familia_escarabajo": "familiaput",
    "Genero_escarabajo": "generoput",
    "Patas_escarabajo": 12,
    "Torax_escarabajo": "toraxput",
    "Ciclo_vida_escarabajo": "ciclo_vidaput",
    "Nombre_comun_escarabajo": "nombre_comunput",
    "Antena_escarabajo": 23,
    "Ojos_escarabajo": "ojosput",
    "Mandibula_escarabajo": "mandibulaput",
    "Alas_escarabajo": "alasput",
    "Elitros_escarabajo": "elitrosput",
    "Audios_escarabajo": [],
    "Imagenes_escarabajo": []
}

###

POST https://localhost:7083/api/escarabajo
Content-Type: application/json

{
    "Especie_escarabajo": "especie123",
    "Familia_escarabajo": "familiaput",
    "Genero_escarabajo": "generoput",
    "Patas_escarabajo": 12,
    "Torax_escarabajo": "toraxput",
    "Ciclo_vida_escarabajo": "ciclo_vidaput",
    "Nombre_comun_escarabajo": "nombre_comunput",
    "Antena_escarabajo": 23,
    "Ojos_escarabajo": "ojosput",
    "Mandibula_escarabajo": "mandibulaput",
    "Alas_escarabajo": "alasput",
    "Elitros_escarabajo": "elitrosput",
    "Audios_escarabajo": [],
    "Imagenes_escarabajo": []
}