GET https://localhost:5001/api/escarabajo
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zaWQiOiIyNzRjY2FjYi03OGU4LTRkMzUtYTEyMS0xYTQ4MWE0MDk4MjMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiTm9tYnJlMiIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkJpb2xvZ28iLCJleHAiOjE3MTcxMTE0NTYsImlzcyI6IlNlcnZpZG9yQ1NoYXJwIiwiYXVkIjoiQ2xpZW50ZUNTaGFycCJ9.bHCAsKIXO1U9FltqEwpQrcwCv6_rM8XVzf-zloktCf0

###

PUT https://localhost:7083/api/escarabajo/put/especie1
Content-Type: application/json

{
    "Especie_escarabajo": "especie1",
    "Familia_escarabajo": "familiaput",
    "Genero_escarabajo": "generoput",
    "Patas_escarabajo": 12,
    "Torax_escarabajo": "toraxput",
    "Ciclo_vida_escarabajo": "ciclo_vidaput",
    "Nombre_comun_escarabajo": "nombre_comunput",
    "Antena_escarabajo": 23,
    "Ojos_escarabajo": "ojosput",
    "Mandibula_escarabajo": "mandibulaput",
    "Alas_escarabajo": "alasput",
    "Elitros_escarabajo": "elitrosput",
    "Audios_escarabajo": [],
    "Imagenes_escarabajo": []
}

###

POST https://localhost:5001/api/escarabajo
Content-Type: application/json

{
    "Especie": "especie123",
    "Familia": "familiaput",
    "Genero": "generoput",
    "Patas": 12,
    "Torax": "toraxput",
    "Ciclo_vida": "ciclo_vidaput",
    "Nombre_comun": "nombre_comunput",
    "Antena": 23,
    "Ojos": "ojosput",
    "Mandibula": "mandibulaput",
    "Alas": "alasput",
    "Elitros": "elitrosput",
    "Descripcion": "descripcionpost",
    "Estado_investigacion": false,
    "Coordenadas": [],
    "Audios": [],
    "Imagenes": []
}