// <auto-generated />
using System;
using BettleHubCsharp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BettleHubCsharp.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240423004715_CreacionInicial")]
    partial class CreacionInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BettleHubCsharp.Models.Biologo", b =>
                {
                    b.Property<string>("Id_biologo")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Contrasena_biologo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Correo_biologo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("Edad_biologo")
                        .HasColumnType("int");

                    b.Property<string>("Nombre_biologo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Protegida")
                        .HasColumnType("tinyint(1)");

                    b.Property<long?>("Telefono_biologo")
                        .HasColumnType("bigint");

                    b.Property<string>("Usuario_biologo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id_biologo");

                    b.ToTable("Biologo");

                    b.HasData(
                        new
                        {
                            Id_biologo = "a4e53e4a-9e37-4dec-8d7f-b260b4750564",
                            Contrasena_biologo = "AQAAAAIAAYagAAAAED3fJ1cEbDnVZ9DhMLXzw2DFTH7I7vvtTP7AkMzfP0uhglKerCwm+Sz480fZxYmO/A==",
                            Correo_biologo = "Correo1",
                            Edad_biologo = 19,
                            Nombre_biologo = "Nombre1",
                            Protegida = true,
                            Telefono_biologo = 9999999999L,
                            Usuario_biologo = "Usuario1"
                        },
                        new
                        {
                            Id_biologo = "b48b3d52-8d99-4639-835a-f5ec62cb3193",
                            Contrasena_biologo = "AQAAAAIAAYagAAAAEPN1cHMhzNuuPMzSXXXUuFIwEIp5jw3kGWMxsPCusev6ohH+dMxHNhRuiLR/lfO2PA==",
                            Correo_biologo = "Correo2",
                            Edad_biologo = 20,
                            Nombre_biologo = "Nombre2",
                            Protegida = true,
                            Telefono_biologo = 9999999999L,
                            Usuario_biologo = "Usuario2"
                        },
                        new
                        {
                            Id_biologo = "3658f92f-ec58-4bfc-882d-ea8c16fdcc47",
                            Contrasena_biologo = "AQAAAAIAAYagAAAAEG9SYhK5OAHT86y21JYcr/ydbUXLmNP8MFiqHJJ0HwFU/fx7+m7Gqf8qH5vmYFY3DA==",
                            Correo_biologo = "Correo3",
                            Edad_biologo = 18,
                            Nombre_biologo = "Nombre3",
                            Protegida = true,
                            Telefono_biologo = 9999999999L,
                            Usuario_biologo = "Usuario3"
                        },
                        new
                        {
                            Id_biologo = "0c443a98-143d-414e-89d3-41987ee947bf",
                            Contrasena_biologo = "AQAAAAIAAYagAAAAEKdZyBTxdZQZ5TErXDyVVNnqnVFraSfdhkk704DYbuT9tA6N0qaYWtOO0A1g/50WuA==",
                            Correo_biologo = "Correo4",
                            Edad_biologo = 23,
                            Nombre_biologo = "Nombre4",
                            Protegida = true,
                            Telefono_biologo = 9999999999L,
                            Usuario_biologo = "Usuario4"
                        });
                });

            modelBuilder.Entity("BettleHubCsharp.Models.DatoCurioso", b =>
                {
                    b.Property<string>("Id_Dato")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Descripcion_Dato")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id_Dato");

                    b.ToTable("DatoCurioso");

                    b.HasData(
                        new
                        {
                            Id_Dato = "a35c6048-65f3-4989-89be-a6e79a1741f9",
                            Descripcion_Dato = "Los Pasalidos son conocidos por su capacidad para producir sonidos, un comportamiento conocido como estridulación."
                        },
                        new
                        {
                            Id_Dato = "e421942e-bb1a-4495-849d-7a3ebfbb4a6b",
                            Descripcion_Dato = "El comportamiento social de los Pasalidos es vivir en grupos familiares donde cooperan en el cuidado de las larvas y el mantenimiento de su hogar."
                        },
                        new
                        {
                            Id_Dato = "b22d8fe1-666c-4864-9ae5-238e1b551315",
                            Descripcion_Dato = "Estos escarabajos son uno de los pocos grupos de coleópteros que exhiben cuidado parental extenso."
                        },
                        new
                        {
                            Id_Dato = "a935a75f-e60a-4793-85de-18866035308a",
                            Descripcion_Dato = "Los Pasalidos ayudan en el ciclo de nutrientes en los ecosistemas forestales."
                        },
                        new
                        {
                            Id_Dato = "d1fa8356-72b2-4050-acc5-a2ec0ccdda3c",
                            Descripcion_Dato = "Aunque principalmente habitan en bosques húmedos y tropicales, tambien habitan bosques templados y áreas montañosas."
                        },
                        new
                        {
                            Id_Dato = "4e5b7d6d-e065-4a13-bf97-26dd146b53fd",
                            Descripcion_Dato = "Los escarabajos de esta familia son xilófagos, lo que significa que se alimentan principalmente de madera."
                        },
                        new
                        {
                            Id_Dato = "e7ccc3e9-0f8c-4516-a9a9-928aed484d18",
                            Descripcion_Dato = "Tienen cuerpos alargados y robustos, cabezas grandes y cuernos que utilizan en sus rituales de apareamiento y en la lucha por territorio o parejas."
                        },
                        new
                        {
                            Id_Dato = "b6135ba9-0a41-48b3-8a1d-1c0beb166f35",
                            Descripcion_Dato = "Estos escarabajos pueden tener ciclos de vida relativamente largos en comparación con otros insectos."
                        },
                        new
                        {
                            Id_Dato = "4b981b0c-e03c-480c-bc6c-e92dbf0478aa",
                            Descripcion_Dato = "Los Pasalidos se encuentran principalmente en las regiones tropicales de América, Asia y África. En América, su distribución va desde México hasta Argentina."
                        },
                        new
                        {
                            Id_Dato = "c6b1a1b0-a817-4bac-82c1-20d2ab1aad85",
                            Descripcion_Dato = "Los Pasalidos son objeto de estudio en áreas como ecología del comportamiento, biología de la conservación y entomología forestal."
                        });
                });

            modelBuilder.Entity("BettleHubCsharp.Models.Escarabajo", b =>
                {
                    b.Property<string>("Especie_escarabajo")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Alas_escarabajo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Antena_escarabajo")
                        .HasColumnType("int");

                    b.Property<string>("Audios_escarabajo")
                        .HasColumnType("longtext");

                    b.Property<string>("Ciclo_vida_escarabajo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Elitros_escarabajo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Familia_escarabajo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Genero_escarabajo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Imagenes_escarabajo")
                        .HasColumnType("longtext");

                    b.Property<string>("Mandibula_escarabajo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre_comun_escarabajo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Ojos_escarabajo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Patas_escarabajo")
                        .HasColumnType("int");

                    b.Property<bool>("Protegida")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Torax_escarabajo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Especie_escarabajo");

                    b.ToTable("Escarabajo");

                    b.HasData(
                        new
                        {
                            Especie_escarabajo = "especie1",
                            Alas_escarabajo = "alas1",
                            Antena_escarabajo = 1,
                            Audios_escarabajo = "[]",
                            Ciclo_vida_escarabajo = "ciclo_vida1",
                            Elitros_escarabajo = "elitros1",
                            Familia_escarabajo = "familia1",
                            Genero_escarabajo = "genero1",
                            Imagenes_escarabajo = "[]",
                            Mandibula_escarabajo = "mandibula1",
                            Nombre_comun_escarabajo = "nombre_comun1",
                            Ojos_escarabajo = "ojos1",
                            Patas_escarabajo = 1,
                            Protegida = true,
                            Torax_escarabajo = "torax1"
                        },
                        new
                        {
                            Especie_escarabajo = "especie2",
                            Alas_escarabajo = "alas2",
                            Antena_escarabajo = 2,
                            Audios_escarabajo = "[]",
                            Ciclo_vida_escarabajo = "ciclo_vida2",
                            Elitros_escarabajo = "elitros2",
                            Familia_escarabajo = "familia2",
                            Genero_escarabajo = "genero2",
                            Imagenes_escarabajo = "[]",
                            Mandibula_escarabajo = "mandibula2",
                            Nombre_comun_escarabajo = "nombre_comun2",
                            Ojos_escarabajo = "ojos2",
                            Patas_escarabajo = 2,
                            Protegida = true,
                            Torax_escarabajo = "torax2"
                        },
                        new
                        {
                            Especie_escarabajo = "especie3",
                            Alas_escarabajo = "alas3",
                            Antena_escarabajo = 3,
                            Audios_escarabajo = "[]",
                            Ciclo_vida_escarabajo = "ciclo_vida3",
                            Elitros_escarabajo = "elitros3",
                            Familia_escarabajo = "familia3",
                            Genero_escarabajo = "genero3",
                            Imagenes_escarabajo = "[]",
                            Mandibula_escarabajo = "mandibula3",
                            Nombre_comun_escarabajo = "nombre_comun3",
                            Ojos_escarabajo = "ojos3",
                            Patas_escarabajo = 3,
                            Protegida = true,
                            Torax_escarabajo = "torax3"
                        },
                        new
                        {
                            Especie_escarabajo = "especie4",
                            Alas_escarabajo = "alas4",
                            Antena_escarabajo = 4,
                            Audios_escarabajo = "[]",
                            Ciclo_vida_escarabajo = "ciclo_vida4",
                            Elitros_escarabajo = "elitros4",
                            Familia_escarabajo = "familia4",
                            Genero_escarabajo = "genero4",
                            Imagenes_escarabajo = "[]",
                            Mandibula_escarabajo = "mandibula4",
                            Nombre_comun_escarabajo = "nombre_comun4",
                            Ojos_escarabajo = "ojos4",
                            Patas_escarabajo = 4,
                            Protegida = true,
                            Torax_escarabajo = "torax4"
                        });
                });

            modelBuilder.Entity("BettleHubCsharp.Models.Pregunta", b =>
                {
                    b.Property<string>("Id_pregunta")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Pregunta_pregunta")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Respuesta_pregunta")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id_pregunta");

                    b.ToTable("Pregunta");

                    b.HasData(
                        new
                        {
                            Id_pregunta = "45e2fb4d-0136-47ca-bd67-fb1154567874",
                            Pregunta_pregunta = "¿Quiénes fueron los desarrolladores?",
                            Respuesta_pregunta = "Somos un grupo de estudiantes de la carrera Lic. Tecnologías Computacionales de la Universidad Veracruzana. Nuestro proyecto Beetle-Finder es un ejemplo sobre nuestro trabajo como desarrolladores, enfocandonos en una comunidad cientifica."
                        },
                        new
                        {
                            Id_pregunta = "c628adb5-756e-45d3-a74d-30afff6ec504",
                            Pregunta_pregunta = "¿Quién es el Dr Edwin Eriza?",
                            Respuesta_pregunta = "Un doctor"
                        },
                        new
                        {
                            Id_pregunta = "d298a8a0-6247-4a2a-9145-6bb93ac8ef31",
                            Pregunta_pregunta = "¿Qué son los Pasalidos?",
                            Respuesta_pregunta = "Los pasálidos son una familia de escarabajos conocidos por su comportamiento social y ecológico, especializados en la descomposición de madera en bosques húmedos y tropicales."
                        },
                        new
                        {
                            Id_pregunta = "ad75e339-d9ce-4344-a845-6b98e8da56f9",
                            Pregunta_pregunta = "¿Quiéres conocer mas sobre otras familias de escarabajos?",
                            Respuesta_pregunta = "Te recomendamos las siguiente paginas para saber mas sobre otras familias. "
                        },
                        new
                        {
                            Id_pregunta = "a87dfb29-16a2-41cc-99ca-01355675fe4a",
                            Pregunta_pregunta = "¿Que hace Bettle-Finder?",
                            Respuesta_pregunta = "Es un paginas web sobre los escarabajos de la familia Passalidae, con la funcion unica de poder clasificar sus sonidos por especie."
                        });
                });

            modelBuilder.Entity("BiologoEscarabajo", b =>
                {
                    b.Property<string>("BiologosId_biologo")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("EscarabajosEspecie_escarabajo")
                        .HasColumnType("varchar(255)");

                    b.HasKey("BiologosId_biologo", "EscarabajosEspecie_escarabajo");

                    b.HasIndex("EscarabajosEspecie_escarabajo");

                    b.ToTable("BiologoEscarabajo");
                });

            modelBuilder.Entity("BiologoEscarabajo", b =>
                {
                    b.HasOne("BettleHubCsharp.Models.Biologo", null)
                        .WithMany()
                        .HasForeignKey("BiologosId_biologo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BettleHubCsharp.Models.Escarabajo", null)
                        .WithMany()
                        .HasForeignKey("EscarabajosEspecie_escarabajo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
