// <auto-generated />
using System;
using BettleHubCsharp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BettleHubCsharp.Migrations
{
    [DbContext(typeof(IdentityContext))]
    partial class IdentityContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BettleHubCsharp.Models.Ayuda", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Ayuda");

                    b.HasData(
                        new
                        {
                            Id = "56f5d0d1-923c-4e3c-ac81-91a98fd85181",
                            Contenido = "Información detallada sobre cómo funciona la página y la tecnología detrás de ella.",
                            Titulo = "Documentacion sobre la pagina"
                        },
                        new
                        {
                            Id = "0a7be0f8-30d4-4e86-b00e-5fc75a02dc45",
                            Contenido = "Descripción general de la aplicación y sus objetivos.",
                            Titulo = "Sobre que trata la aplicacion"
                        },
                        new
                        {
                            Id = "9893e337-e3c3-4590-b011-f77e250b140e",
                            Contenido = "Respuestas a las preguntas más frecuentes sobre el uso de la plataforma.",
                            Titulo = "Preguntas generales"
                        },
                        new
                        {
                            Id = "ce8c7a26-f2a1-4493-b3fd-f99ab4d15051",
                            Contenido = "Una pequeña guía paso a paso sobre cómo utilizar las principales características de la aplicación.",
                            Titulo = "Guia de uso"
                        });
                });

            modelBuilder.Entity("BettleHubCsharp.Models.Biologo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<int?>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Protegida")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<long?>("Telefono")
                        .HasColumnType("bigint");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "68030228-1327-49e8-bcdf-e61629061987",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b7be226e-74ee-4459-a7bb-62a38df556f4",
                            Edad = 19,
                            Email = "Correo1@correo.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "CORREO1@CORREO.COM",
                            NormalizedUserName = "NOMBRE1",
                            PasswordHash = "AQAAAAIAAYagAAAAEJ6Xz92wV2W2Y+XB9OhQkIDIR1onqWveamPh4v38TNDOd87FqMd7C48hAGu3wP57Xw==",
                            PhoneNumberConfirmed = false,
                            Protegida = true,
                            SecurityStamp = "453abacc-304c-44e7-a18a-a4942e6b3845",
                            Telefono = 9999999999L,
                            TwoFactorEnabled = false,
                            UserName = "Nombre1"
                        },
                        new
                        {
                            Id = "32631526-be33-4b21-84b1-8a7eeec0afc2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "54698dca-9870-4619-ae9e-19307753f817",
                            Edad = 20,
                            Email = "Correo2@correo.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "CORREO2@CORREO.COM",
                            NormalizedUserName = "Nombre2",
                            PasswordHash = "AQAAAAIAAYagAAAAECnU/k82W5efH7zuxKQ30eoUP4SAxMAfw+BHjVM37qKjjwSsI8WjbsJGjfT/rNa8eg==",
                            PhoneNumberConfirmed = false,
                            Protegida = false,
                            SecurityStamp = "25239d28-ed47-4574-b275-5a5f9b8c9b06",
                            Telefono = 9999999999L,
                            TwoFactorEnabled = false,
                            UserName = "Nombre2"
                        });
                });

            modelBuilder.Entity("BettleHubCsharp.Models.DatoCurioso", b =>
                {
                    b.Property<string>("Id_Dato")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Descripcion_Dato")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id_Dato");

                    b.ToTable("DatoCurioso");

                    b.HasData(
                        new
                        {
                            Id_Dato = "2448f470-1c99-4d2f-90ec-31f49abc44d0",
                            Descripcion_Dato = "Los Pasalidos son conocidos por su capacidad para producir sonidos, un comportamiento conocido como estridulación."
                        },
                        new
                        {
                            Id_Dato = "bd602b2a-906f-4d5f-a2cc-b6735ff2068f",
                            Descripcion_Dato = "El comportamiento social de los Pasalidos es vivir en grupos familiares donde cooperan en el cuidado de las larvas y el mantenimiento de su hogar."
                        },
                        new
                        {
                            Id_Dato = "a31b4db2-76a2-47be-a379-97740cd5cae3",
                            Descripcion_Dato = "Estos escarabajos son uno de los pocos grupos de coleópteros que exhiben cuidado parental extenso."
                        },
                        new
                        {
                            Id_Dato = "6e300a9a-9292-4c09-8f35-6cc19da5c943",
                            Descripcion_Dato = "Los Pasalidos ayudan en el ciclo de nutrientes en los ecosistemas forestales."
                        },
                        new
                        {
                            Id_Dato = "9c7d2b23-bc34-4127-a0b1-39c623b267e1",
                            Descripcion_Dato = "Aunque principalmente habitan en bosques húmedos y tropicales, tambien habitan bosques templados y áreas montañosas."
                        },
                        new
                        {
                            Id_Dato = "9b942bc1-451e-436d-b4c1-8b8abfd6fd42",
                            Descripcion_Dato = "Los escarabajos de esta familia son xilófagos, lo que significa que se alimentan principalmente de madera."
                        },
                        new
                        {
                            Id_Dato = "a391d877-c63e-402c-bfb3-bc00f5b4e93b",
                            Descripcion_Dato = "Tienen cuerpos alargados y robustos, cabezas grandes y cuernos que utilizan en sus rituales de apareamiento y en la lucha por territorio o parejas."
                        },
                        new
                        {
                            Id_Dato = "cc96120d-0824-449d-9cd8-bf88f2215194",
                            Descripcion_Dato = "Estos escarabajos pueden tener ciclos de vida relativamente largos en comparación con otros insectos."
                        },
                        new
                        {
                            Id_Dato = "15fd2d50-815d-4a04-a5c9-bd07d4060761",
                            Descripcion_Dato = "Los Pasalidos se encuentran principalmente en las regiones tropicales de América, Asia y África. En América, su distribución va desde México hasta Argentina."
                        },
                        new
                        {
                            Id_Dato = "b6580d15-c826-43a1-88f8-18391be4f420",
                            Descripcion_Dato = "Los Pasalidos son objeto de estudio en áreas como ecología del comportamiento, biología de la conservación y entomología forestal."
                        });
                });

            modelBuilder.Entity("BettleHubCsharp.Models.Escarabajo", b =>
                {
                    b.Property<string>("Especie")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Alas")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Antena")
                        .HasColumnType("int");

                    b.Property<string>("Audios")
                        .HasColumnType("longtext");

                    b.Property<string>("Ciclo_vida")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Coordenadas")
                        .HasColumnType("longtext");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Elitros")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Estado_investigacion")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Familia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Imagenes")
                        .HasColumnType("longtext");

                    b.Property<string>("Mandibula")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre_comun")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Ojos")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Patas")
                        .HasColumnType("int");

                    b.Property<bool>("Protegida")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Torax")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Especie");

                    b.ToTable("Escarabajo");

                    b.HasData(
                        new
                        {
                            Especie = "especie1",
                            Alas = "alas1",
                            Antena = 1,
                            Audios = "[\"./css/resources/audios/junctistriatus/P_junctistriatus_6_2.wav\"]",
                            Ciclo_vida = "ciclo_vida1",
                            Coordenadas = "[\"19.5450165,-96.8953113,14\"]",
                            Descripcion = "Los escarabajos pasálidos, también conocidos como escarabajos de tierra, son insectos coleópteros que se caracterizan por su cuerpo ovalado y duro, así como por sus antenas cortas y robustas.",
                            Elitros = "elitros1",
                            Estado_investigacion = false,
                            Familia = "familia1",
                            Genero = "genero1",
                            Imagenes = "[\"./css/resources/images/pasalido1.jpg\"]",
                            Mandibula = "mandibula1",
                            Nombre_comun = "nombre_comun1",
                            Ojos = "ojos1",
                            Patas = 1,
                            Protegida = true,
                            Torax = "torax1"
                        },
                        new
                        {
                            Especie = "especie2",
                            Alas = "alas2",
                            Antena = 2,
                            Audios = "[\"./css/resources/audios/junctistriatus/P_junctistriatus_6_2.wav\"]",
                            Ciclo_vida = "ciclo_vida2",
                            Coordenadas = "[\"17.0794635,-96.7063748,17\"]",
                            Descripcion = "Los escarabajos pasálidos: pequeños guardianes del suelo. Estos insectos, con su armadura brillante y patas fuertes, son esenciales para mantener el equilibrio del ecosistema del suelo al descomponer materia orgánica y aerar el sustrato.",
                            Elitros = "elitros2",
                            Estado_investigacion = false,
                            Familia = "familia2",
                            Genero = "genero2",
                            Imagenes = "[\"./css/resources/images/pasalido2.jpg\"]",
                            Mandibula = "mandibula2",
                            Nombre_comun = "nombre_comun2",
                            Ojos = "ojos2",
                            Patas = 2,
                            Protegida = true,
                            Torax = "torax2"
                        },
                        new
                        {
                            Especie = "especie3",
                            Alas = "alas3",
                            Antena = 3,
                            Audios = "[\"./css/resources/audios/subopacus/P_subopacus_5_3.wav\"]",
                            Ciclo_vida = "ciclo_vida3",
                            Coordenadas = "[\"19.4973646,-96.8573872,16\"]",
                            Descripcion = "Los escarabajos pasálidos son criaturas fascinantes que se encuentran en una variedad de hábitats terrestres. Su papel como descomponedores es crucial para el ciclo de nutrientes, contribuyendo al proceso de compostaje y enriqueciendo la salud del suelo.",
                            Elitros = "elitros3",
                            Estado_investigacion = false,
                            Familia = "familia3",
                            Genero = "genero3",
                            Imagenes = "[\"./css/resources/images/pasalido3.jpg\"]",
                            Mandibula = "mandibula3",
                            Nombre_comun = "nombre_comun3",
                            Ojos = "ojos3",
                            Patas = 3,
                            Protegida = true,
                            Torax = "torax3"
                        },
                        new
                        {
                            Especie = "especie4",
                            Alas = "alas4",
                            Antena = 4,
                            Audios = "[\"./css/resources/audios/zuninoi/P_zuninoi_3_6.wav\"]",
                            Ciclo_vida = "ciclo_vida4",
                            Coordenadas = "[\"19.5266079,-96.9242194,17\"]",
                            Descripcion = "Descubre el mundo subterráneo de los escarabajos pasálidos. Estos pequeños insectos, con su caparazón brillante y su actividad incansable, desempeñan un papel vital en la transformación de materia orgánica en nutrientes disponibles para otras formas de vida en el suelo.",
                            Elitros = "elitros4",
                            Estado_investigacion = false,
                            Familia = "familia4",
                            Genero = "genero4",
                            Imagenes = "[\"./css/resources/images/pasalido4.jpg\"]",
                            Mandibula = "mandibula4",
                            Nombre_comun = "nombre_comun4",
                            Ojos = "ojos4",
                            Patas = 4,
                            Protegida = true,
                            Torax = "torax4"
                        });
                });

            modelBuilder.Entity("BettleHubCsharp.Models.Pregunta", b =>
                {
                    b.Property<string>("Id_pregunta")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Pregunta_pregunta")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Respuesta_pregunta")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id_pregunta");

                    b.ToTable("Pregunta");

                    b.HasData(
                        new
                        {
                            Id_pregunta = "98295b1a-4c52-4750-839f-f3144f6eb23f",
                            Pregunta_pregunta = "¿Quiénes fueron los desarrolladores?",
                            Respuesta_pregunta = "Somos un grupo de estudiantes de la carrera Lic. Tecnologías Computacionales de la Universidad Veracruzana. Nuestro proyecto Beetle-Finder es un ejemplo sobre nuestro trabajo como desarrolladores, enfocandonos en una comunidad cientifica."
                        },
                        new
                        {
                            Id_pregunta = "dba0498c-1334-4c13-abf7-08ffec4bd3e9",
                            Pregunta_pregunta = "¿Quién es el Dr Edwin Eriza?",
                            Respuesta_pregunta = "Un doctor"
                        },
                        new
                        {
                            Id_pregunta = "3fcb3926-8ef6-4209-af60-e1ae2bf117f3",
                            Pregunta_pregunta = "¿Qué son los Pasalidos?",
                            Respuesta_pregunta = "Los pasálidos son una familia de escarabajos conocidos por su comportamiento social y ecológico, especializados en la descomposición de madera en bosques húmedos y tropicales."
                        },
                        new
                        {
                            Id_pregunta = "013b8a07-bf4e-4f96-8911-e4ad259dda97",
                            Pregunta_pregunta = "¿Quiéres conocer mas sobre otras familias de escarabajos?",
                            Respuesta_pregunta = "Te recomendamos las siguiente paginas para saber mas sobre otras familias. "
                        },
                        new
                        {
                            Id_pregunta = "44d80f95-e4c3-44aa-805d-4b8ce17f5651",
                            Pregunta_pregunta = "¿Que hace Bettle-Finder?",
                            Respuesta_pregunta = "Es un paginas web sobre los escarabajos de la familia Passalidae, con la funcion unica de poder clasificar sus sonidos por especie."
                        });
                });

            modelBuilder.Entity("BiologoEscarabajo", b =>
                {
                    b.Property<string>("BiologosId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("EscarabajosEspecie")
                        .HasColumnType("varchar(255)");

                    b.HasKey("BiologosId", "EscarabajosEspecie");

                    b.HasIndex("EscarabajosEspecie");

                    b.ToTable("BiologoEscarabajo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "d4e39185-637e-4b70-a129-7c5be1618071",
                            Name = "Administrador",
                            NormalizedName = "ADMINISTRADOR"
                        },
                        new
                        {
                            Id = "8881ab90-7112-4808-ac52-25ee9b4125d2",
                            Name = "Biologo",
                            NormalizedName = "BIOLOGO"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "68030228-1327-49e8-bcdf-e61629061987",
                            RoleId = "d4e39185-637e-4b70-a129-7c5be1618071"
                        },
                        new
                        {
                            UserId = "32631526-be33-4b21-84b1-8a7eeec0afc2",
                            RoleId = "8881ab90-7112-4808-ac52-25ee9b4125d2"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BiologoEscarabajo", b =>
                {
                    b.HasOne("BettleHubCsharp.Models.Biologo", null)
                        .WithMany()
                        .HasForeignKey("BiologosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BettleHubCsharp.Models.Escarabajo", null)
                        .WithMany()
                        .HasForeignKey("EscarabajosEspecie")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BettleHubCsharp.Models.Biologo", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BettleHubCsharp.Models.Biologo", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BettleHubCsharp.Models.Biologo", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BettleHubCsharp.Models.Biologo", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
